# Generated by Django 2.2 on 2020-11-01 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
